name: Pull and Test Docker Image

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'data/**'
      - 'requirements.txt'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    needs: train
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Pull Docker Image
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/diagnosis_test:latest
 
    - name: Run Docker Image Check Score
      run: |
        # Run the docker image and evaluate if threshold is met
        score=$(docker run ${{ secrets.DOCKER_USERNAME }}/diagnosis_test:latest)
        if (( $(echo "$score > 0.50" | bc -l) )); then
          echo "Score is greater than 0.50"
          exit 0
        else
          echo "Score is not greater than 0.50"
          exit 1
        fi
